---
lowercaseOutputLabelNames: true
lowercaseOutputName: true
startDelaySeconds: 0
#hostPort: 127.0.0.1:7199
username:
password:
#jmxUrl: service:jmx:rmi:///jndi/rmi://127.0.0.1:7199/jmxrmi
ssl: false
whitelistObjectNames:
  - "org.apache.cassandra.metrics:*"
  - "org.apache.cassandra.db:*"
  - "org.apache.cassandra.net:*"
  - "org.apache.cassandra.internal:*"
  - "org.apache.cassandra.metrics:type=ThreadPools"
blacklistObjectNames:
  - "org.apache.cassandra.metrics:type=ColumnFamily,*"



# commented out - this is the original setup, but it's too generic
# we don't get any useful info from this, but it's helpful as a reference
#  - pattern: 'org.apache.cassandra.metrics<type=(\w+), name=(\w+)><>Value: (\d+)'
#    name: cassandra_$1_$2
#    value: $3
#    valueFactor: 0.001
#    labels: {}
#    help: "Cassandra metric $1 $2"
#    type: GAUGE
#    attrNameSnakeCase: false
